tasks:
 - echo 'USE_SQLITE=True' > tests/local.py
 - tox -e flake8
 - tox -e isort
 - tox -e py27-django14
 - tox -e py27-django15
 - tox -e py27-django16
 - tox -e py27-django17
 - tox -e py27-django18
 - tox -e py34-django15
 - tox -e py34-django16
 - tox -e py34-django17
 - tox -e py34-django18
 - tox -e py34-django19
 - coverage combine && coverage report && coverage xml

coverage:
  path: coverage.xml
  parser: python
